"""initial schema

Revision ID: f1cbfcc4819c
Revises: 
Create Date: 2026-09-27 18:18:04.027993

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cbfcc4819c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('book', sa.Enum('SOURCE', 'MODEL', 'PLATFORM', 'FOLLOWER', name='book', native_enum=False), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='side', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_authority', sa.String(), nullable=False),
    sa.Column('reconciliation_state', sa.Enum('UNRECONCILED', 'RECONCILED', 'DISPUTED', name='reconciliationstate', native_enum=False), nullable=False),
    sa.Column('correction_of', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['correction_of'], ['ledger_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_ledger_entries_tenant_id'), 'ledger_entries', ['tenant_id'], unique=False)
    op.create_table('portfolio_versions',
    sa.Column('portfolio_version_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('cash_weight', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('research_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_subscriber_capacity', sa.Integer(), nullable=False),
    sa.Column('consent_disclosure_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_version_id')
    )
    op.create_index(op.f('ix_portfolio_versions_portfolio_id'), 'portfolio_versions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_versions_tenant_id'), 'portfolio_versions', ['tenant_id'], unique=False)
    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('publication_intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('LOCAL_SIM', 'INTEGRATION_ISOLATED', 'PLATFORM_DEMO', 'PRIVATE_SHADOW', 'COMMERCIAL_LIVE', name='environment', native_enum=False), nullable=False),
    sa.Column('portfolio_version_id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('OPEN', 'ADD', 'REDUCE', 'CLOSE', 'STOP_UPDATE', 'TARGET_UPSERT', 'TARGET_REMOVE', 'TARGET_CLEAR', 'ENTRY_CANCEL', 'STATUS_CORRECTION', 'STRATEGY_PAUSE', name='publicationaction', native_enum=False), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('external_strategy_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('quantity_basis', sa.Enum('UNITS', 'CONTRACTS', 'ORIGINAL_FRACTION', 'REMAINING_FRACTION', 'TARGET_POSITION', 'NOT_APPLICABLE', name='quantitybasis', native_enum=False), nullable=False),
    sa.Column('price_basis', sa.String(), nullable=False),
    sa.Column('policy_hash', sa.String(), nullable=False),
    sa.Column('audience_snapshot_hash', sa.String(), nullable=False),
    sa.Column('source_revision_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rights_grant_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('body_hash', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'ELIGIBLE', 'QUEUED', 'SENDING', 'ACKNOWLEDGED', 'UNKNOWN', 'REJECTED', 'RECONCILING', 'SUPERSEDED', 'TERMINAL', name='publicationstate', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('channel', 'external_strategy_id', 'portfolio_version_id', 'action', 'revision', name='uq_publication_intent_natural_key'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('publisher_writer_claims',
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('external_strategy_id', sa.String(), nullable=False),
    sa.Column('writer_identity', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel', 'external_strategy_id')
    )
    op.create_table('rights_grants',
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('grantee_entity', sa.String(), nullable=False),
    sa.Column('contract_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'GRANTED', 'DENIED', 'REVOKED', name='rightsstatus', native_enum=False), nullable=False),
    sa.Column('uses', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('jurisdictions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('assets', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attribution_policy_id', sa.String(), nullable=False),
    sa.Column('wind_down_policy_id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_rights_grants_source_id'), 'rights_grants', ['source_id'], unique=False)
    op.create_table('sleeves',
    sa.Column('sleeve_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('analyst', sa.String(), nullable=False),
    sa.Column('strategy_horizon', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('execution_policy_id', sa.String(), nullable=False),
    sa.Column('cost_model_id', sa.String(), nullable=False),
    sa.Column('capacity_policy_id', sa.String(), nullable=False),
    sa.Column('risk_unit_id', sa.String(), nullable=False),
    sa.Column('history_origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sleeve_id')
    )
    op.create_index(op.f('ix_sleeves_tenant_id'), 'sleeves', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('FREE_RESEARCH', 'ALERTS_ONE', 'PORTFOLIOS_THREE', 'PRO_RESEARCH_API', name='producttier', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('PENDING_PAYMENT', 'TRIAL_AUTHORIZED', 'ACTIVE_PAID', 'CANCEL_AT_PERIOD_END', 'PAST_DUE', 'SUSPENDED_NEW_ENTRIES', 'ENDED', 'DISPUTED', 'MANUAL_REVIEW', name='subscriptionstate', native_enum=False), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processor_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('user_identities',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('memberships',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'RESEARCHER', 'REVIEWER', 'PUBLISHER_OPERATOR', 'BILLING_OPERATOR', 'SUPPORT_READONLY', 'CUSTOMER', name='membershiprole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_identities.user_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_table('portfolio_version_sleeves',
    sa.Column('portfolio_version_id', sa.String(), nullable=False),
    sa.Column('sleeve_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_version_id'], ['portfolio_versions.portfolio_version_id'], ),
    sa.ForeignKeyConstraint(['sleeve_id'], ['sleeves.sleeve_id'], ),
    sa.PrimaryKeyConstraint('portfolio_version_id', 'sleeve_id')
    )
    op.create_table('customer_profiles',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('residence_jurisdiction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['memberships.tenant_id', 'memberships.user_id'], name='fk_customer_profile_membership'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_profiles')
    op.drop_table('portfolio_version_sleeves')
    op.drop_table('memberships')
    op.drop_table('user_identities')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sleeves_tenant_id'), table_name='sleeves')
    op.drop_table('sleeves')
    op.drop_index(op.f('ix_rights_grants_source_id'), table_name='rights_grants')
    op.drop_table('rights_grants')
    op.drop_table('publisher_writer_claims')
    op.drop_table('publication_intents')
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_portfolio_versions_tenant_id'), table_name='portfolio_versions')
    op.drop_index(op.f('ix_portfolio_versions_portfolio_id'), table_name='portfolio_versions')
    op.drop_table('portfolio_versions')
    op.drop_index(op.f('ix_ledger_entries_tenant_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
