'use strict';
const data=JSON.parse(document.getElementById('atlas-data').textContent);
const byId=Object.fromEntries(data.screens.map(s=>[s.id,s]));
const fieldById=Object.fromEntries(data.forms.map(f=>[f.id,f]));
let selected='TR-01', view='layout', uiState='empty';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=text;if(cls)n.className=cls;return n;};
const get=id=>document.getElementById(id);
const clear=n=>n.replaceChildren();
function append(parent,tag,text,cls){const n=el(tag,text,cls);parent.append(n);return n;}
function button(text,handler,cls){const n=el('button',text,cls);n.type='button';n.addEventListener('click',handler);return n;}
function table(headers,rows){const box=el('div',null,'table-wrap'),t=el('table');box.append(t);const cap=el('caption','Design contract. No account or market data is connected.');t.append(cap);const head=el('thead'),tr=el('tr');headers.forEach(x=>{const th=el('th',x);th.scope='col';tr.append(th)});head.append(tr);t.append(head);const body=el('tbody');rows.forEach(r=>{const row=el('tr');r.forEach(x=>row.append(el('td',x)));body.append(row)});t.append(body);return box;}
function buildNav(query=''){const n=get('nav-list');clear(n);const groups=[['public','Public website'],['identity','Identity'],['customer','Customer portal'],['trading','Private trading'],['admin','Admin and research']];for(const[g,title]of groups){const list=data.screens.filter(s=>s.surface===g&&([s.id,s.title,s.purpose,...s.forms.flatMap(fid=>[fieldById[fid].title,...fieldById[fid].fields.map(f=>f.label)])].join(' ')).toLowerCase().includes(query.toLowerCase()));if(!list.length)continue;const d=el('details');d.open=innerWidth>=768||byId[selected].surface===g||!!query;d.append(el('summary',`${title} (${list.length})`));list.forEach(s=>{const b=button(s.title,()=>select(s.id));b.dataset.screen=s.id;b.append(el('small',s.id+' · '+s.page_path));if(s.id===selected)b.setAttribute('aria-current','page');d.append(b)});n.append(d);}}
function select(id){if(!byId[id])return;selected=id;history.replaceState(null,'','#'+id);render();buildNav(get('search').value);document.title=byId[id].title+' · Dashboard design';}
function inspectAction(a){const d=get('action-inspector');d.classList.remove('hidden');clear(d);append(d,'h2',a.label+' · '+a.id);append(d,'p',a.behavior);append(d,'p','Binding: '+(a.api_id||a.target_screen||(a.form_ids||[]).join(', ')||a.detail_route_key),'mono');append(d,'p','This is the design reference, not a submitted command. No record, payment, signal or order was created.','muted');if(a.target_screen)d.append(button('Inspect target screen',()=>select(a.target_screen)));d.scrollIntoView({block:'nearest'});}
function metricCards(s,parent){if(!s.metrics.length)return;const row=el('div',null,'row');for(const label of s.metrics){const card=el('div',null,'metric');append(card,'div',label,'label');append(card,'div','—','value');append(card,'div','No evidence connected','tiny muted');row.append(card)}parent.append(row);}
function renderLayout(s){const parent=get('view');const notice=el('div',null,'notice');append(notice,'h2',uiState==='empty'?s.empty_heading:data.states[uiState].heading);append(notice,'p',uiState==='empty'?'Valid empty state. The production screen must query the real scoped repository; it must not fabricate portfolios, returns or balances.':data.states[uiState].render);append(notice,'p','Mode shown: '+uiState+'. All values below are intentionally unavailable in this offline reference.','tiny muted');parent.append(notice);const actions=el('div',null,'row screen-actions');data.actions.filter(a=>a.screen===s.id).forEach(a=>actions.append(button(a.label,()=>inspectAction(a))));parent.append(actions);metricCards(s,parent);const grid=el('div',null,'grid');grid.style.marginTop='22px';for(let i=0;i<s.panels.length;i++){const p=s.panels[i];const pd=data.panels.find(x=>x.screen===s.id&&x.order===i+1);const card=el('section',null,'panel '+((i===0&&s.panels.length>1)?'span8':i===1?'span4':'span12'));append(card,'h2',p);const lower=p.toLowerCase();if(pd.component==='chart'){const chart=el('div',null,'chart-placeholder');append(chart,'strong','No verified series available');append(chart,'p','Render the chart only when its scoped report contains eligible data. Keep origin, period, fees and quality visible.');append(chart,'span','Accessible data table uses the same metric definitions.','tiny muted');card.append(chart);}else if(['table','timeline'].includes(pd.component)&&s.columns.length){card.append(table(s.columns,[s.columns.map((_,j)=>j===0?'No records in this design reference':'—')]));}else if(pd.component==='checklist'){append(card,'p','Show independently evaluated prerequisites, effective settings and precise blockers.','muted');['Identity and scope','Applicable evidence','Permitted next action'].forEach(x=>{const line=el('div',null,'row');append(line,'span',x);append(line,'span','Not evaluated','badge');card.append(line)});}else{append(card,'p',pd.description,'muted');append(card,'p',pd.empty_copy,'tiny muted');}grid.append(card);}parent.append(grid);const next=el('div',null,'panel');next.style.marginTop='20px';append(next,'h2','Empty-state next step');append(next,'p',byId[s.empty_next].title+' · '+byId[s.empty_next].page_path);next.append(button('Inspect this next screen',()=>select(s.empty_next)));parent.append(next);}
function renderFields(s){const parent=get('view');if(!s.forms.length){append(parent,'div','This is a read/navigation screen. Use the specified actions to reach its scoped configuration workflow.','empty');return;}for(const fid of s.forms){const f=fieldById[fid];const outer=el('section',null,'panel');outer.style.marginBottom='20px';append(outer,'h2',f.title+' · '+fid);const steps=el('div');f.steps.forEach((x,i)=>append(steps,'span',String(i+1)+'. '+x,'formstep'));outer.append(steps);const split=el('div',null,'split-form'),fields=el('div',null,'field-grid');for(const field of f.fields){const w=el('div',null,'field');const label=el('label',field.label+(field.required?' *':''));const id=fid+'-'+field.key;label.htmlFor=id;let input;const type=field.type;if(type.startsWith('enum:')){input=el('select');input.append(el('option','Select an allowed value'));type.split(':')[1].split(',').forEach(v=>{const o=el('option',v);o.value=v;input.append(o)});}else if(type==='boolean'){input=el('input');input.type='checkbox';}else if(type==='password'){input=el('input');input.type='password';input.autocomplete='off';input.placeholder='No real credential in design viewer';}else if(type==='weight_map'||field.key==='description'||field.key==='body'){input=el('textarea');input.placeholder='Design reference only';}else{input=el('input');input.type='text';input.placeholder=field.default===null?'Unset until provided/derived':String(field.default)+' (proposed default)';}input.id=id;input.dataset.field=field.key;input.setAttribute('aria-describedby',id+'-help');const help=el('small',field.validation+'. '+field.help,'help');help.id=id+'-help';w.append(label,input,help);fields.append(w);}split.append(fields);const rail=el('aside',null,'summary-rail');append(rail,'h3','Effective settings and authority');append(rail,'p','Show inherited value, draft value, hard bound, provenance and whether the setting affects existing exposure.');append(rail,'p','Save: '+f.save_effect,'tiny');append(rail,'p','Preview: '+f.preview_effect,'tiny');append(rail,'p','Confirm: '+f.confirm_effect,'tiny');split.append(rail);outer.append(split);const bar=el('div',null,'action-bar');for(const label of ['Inspect save contract','Inspect preview contract','Inspect confirmation contract'])bar.append(button(label,()=>{const detail=el('div',null,'notice');append(detail,'strong','Reference only. No request was submitted.');append(detail,'p',label.includes('save')?f.save_effect:label.includes('preview')?f.preview_effect:f.confirm_effect);outer.append(detail)}));outer.append(bar);parent.append(outer);}}
function renderContract(s){const parent=get('view');for(const[title,value]of [['Purpose',s.purpose],['Page and read API',s.page_path+'\n'+s.read_path],['Authority',s.read_roles.join(', ')+'; '+s.read_scope],['Acceptance',s.acceptance],['Layout',JSON.stringify(s.layout,null,2)],['Data and presentation',s.refresh+'\n'+s.cache+'\n'+s.effects]]){const block=el('section',null,'spec-block');append(block,'h2',title);append(block,title==='Layout'?'pre':'p',value);parent.append(block);}const api=data.api.filter(a=>(a.screens||[]).includes(s.id)||(s.forms.includes(a.form_id)&&a.service===s.service));parent.append(table(['Method','Path','Status','Permission'],api.map(a=>[a.method,a.path,a.status,(a.permission||[]).join(', ')])));append(parent,'p','Use screens/'+s.id+'.md and catalog/actions.json for complete action and field bindings.','muted');}
function render(){const s=byId[selected];get('screen-id').textContent=s.id+' · '+s.surface;get('screen-title').textContent=s.title;get('screen-purpose').textContent=s.purpose;get('page-route').textContent=s.page_path;get('roles').textContent='Access: '+s.read_roles.join(', ');get('reqs').textContent=s.requirements.join(' · ')||'Private execution scope';get('state-select').value=uiState;clear(get('view'));get('action-inspector').classList.add('hidden');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===view)));if(view==='layout')renderLayout(s);else if(view==='fields')renderFields(s);else renderContract(s);get('screen-status').textContent='Designed, not application-tested';}
get('search').addEventListener('input',e=>buildNav(e.target.value));get('state-select').addEventListener('change',e=>{uiState=e.target.value;render()});get('theme-select').addEventListener('change',e=>document.documentElement.dataset.theme=e.target.value);document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render()}));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.home)));
window.atlas={select,setState:value=>{if(!data.states[value])throw Error('Unknown state');uiState=value;render()},setView:value=>{if(!['layout','fields','contract'].includes(value))throw Error('Unknown view');view=value;render()},screenIds:data.screens.map(s=>s.id)};
selected=byId[location.hash.slice(1)]?location.hash.slice(1):'TR-01';render();buildNav();
