"""Backs ID-01/ID-02/ID-03 (dashboard_spec/screens/) -- see
app/services/local_auth.py's own module docstring for what this is
(a real, working local credential system for THIS deployment) and is
not (a Supabase Auth integration, a real production deployment's own
external task).

Neither table here is tenant-scoped (see this migration's own
docstring, alembic/versions/a1b2c3d4e5f6_*): a token/session row is
looked up BEFORE its tenant/role is known.
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Enum, ForeignKey, ForeignKeyConstraint, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.now(timezone.utc)


class AuthTokenType(str, enum.Enum):
    EMAIL_VERIFICATION = "email_verification"
    PASSWORD_RESET = "password_reset"


class AuthToken(Base):
    """A single-use, expiring token -- the token STRING itself is the
    primary key (a high-entropy `secrets.token_urlsafe`, generated by
    app/services/local_auth.py, never guessable), matching
    signal-copier's own app/auth.py `create_session` precedent of using
    the random value itself as the lookup key rather than a separate
    opaque id."""

    __tablename__ = "auth_tokens"

    token: Mapped[str] = mapped_column(String, primary_key=True)
    user_id: Mapped[str] = mapped_column(ForeignKey("user_identities.user_id"), nullable=False)
    token_type: Mapped[AuthTokenType] = mapped_column(Enum(AuthTokenType, native_enum=False), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class WebSession(Base):
    """A server-side, revocable browser session -- carried as an
    httponly cookie holding `session_id`, plus a separate CSRF token
    returned once in the login/verify response body. Same two-part
    design as signal-copier's own app/auth.py, for the same reason (see
    that module's own docstring's "Why a session cookie AND a separate
    CSRF token" section)."""

    __tablename__ = "web_sessions"

    session_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    tenant_id: Mapped[str] = mapped_column(String, nullable=False)
    #: Stored as the plain MembershipRole value string -- this table
    #: deliberately doesn't import app.models.tenancy.MembershipRole to
    #: avoid a circular import; app/services/local_auth.py validates it.
    role: Mapped[str] = mapped_column(String, nullable=False)
    csrf_token: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "user_id"], ["memberships.tenant_id", "memberships.user_id"]),
    )
