"""Alembic environment -- imports every model module so `Base.metadata`
is fully populated (mirrors tests/conftest.py's own reasoning: importing
only the modules a given script happens to touch would silently drop
tables from an autogenerated diff), and resolves the database URL from
`ALEMBIC_DATABASE_URL` (when a caller needs migrations to target a
specific, possibly disposable, database) or else `app.config.COMMERCIAL_DATABASE_URL`
-- never a URL hardcoded in alembic.ini.
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app import config as app_config
from app.db import Base

import app.models.billing  # noqa: E402,F401
import app.models.ledger  # noqa: E402,F401
import app.models.portfolio_version  # noqa: E402,F401
import app.models.product  # noqa: E402,F401
import app.models.publication  # noqa: E402,F401
import app.models.publisher_writer_claim  # noqa: E402,F401
import app.models.release_review  # noqa: E402,F401
import app.models.research_run  # noqa: E402,F401
import app.models.rights  # noqa: E402,F401
import app.models.sleeve  # noqa: E402,F401
import app.models.tenancy  # noqa: E402,F401
import app.models.webhook_event  # noqa: E402,F401

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

_database_url = os.environ.get("ALEMBIC_DATABASE_URL", app_config.COMMERCIAL_DATABASE_URL)
config.set_main_option("sqlalchemy.url", _database_url)


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
